import { StenoDictionaryLike } from './steno-dictionary.js';
import { asyncPython, PythonWasmAsync } from '../../vendor/python-wasm/dist/node.js';

type PythonRuntime = PythonWasmAsync;

export function buildPythonDictionarySource(entries: Array<[string[], string]>): string {
  const longest = Math.max(1, ...entries.map(([stroke]) => stroke.length || 1));
  const lines = [
    '# Auto-generated by Stripped Plover',
    `LONGEST_KEY = ${longest}`,
    '',
    'DICTIONARY = {',
  ];

  const escape = (value: string) => value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const tupleLiteral = (stroke: string[]) => {
    const body = stroke.map(s => `'${escape(s)}'`).join(', ');
    return `(${body}${stroke.length === 1 ? ',' : ''})`;
  };

  for (const [stroke, translation] of entries) {
    lines.push(`    ${tupleLiteral(stroke)}: ${JSON.stringify(translation)},`);
  }

  lines.push(
    '}',
    '',
    'def lookup(key):',
    '    if key in DICTIONARY:',
    '        return DICTIONARY[key]',
    '    raise KeyError(key)',
    '',
    'def reverse_lookup(value):',
    '    return [k for k, v in DICTIONARY.items() if v == value]',
    ''
  );

  return lines.join('\n');
}

/**
 * Python Dictionary implementation that executes Python code via python-wasm.
 */
export class PythonDictionary implements StenoDictionaryLike {
  private _path: string;
  private _py: PythonRuntime | null = null;
  private _longestKey = 0;
  private _hasReverseLookup = false;
  private _entries: Array<[string[], string]> = [];
  private _length = -1;
  readonly = true;
  enabled: boolean;

  private constructor(path: string, enabled = true) {
    this._path = path;
    this.enabled = enabled;
  }

  static async loadFromCode(code: string, options: { path?: string; enabled?: boolean } = {}): Promise<PythonDictionary> {
    const dict = new PythonDictionary(options.path ?? ':memory:', options.enabled ?? true);
    await dict.loadFromPython(code);
    return dict;
  }

  private async loadFromPython(code: string): Promise<void> {
    const py: PythonRuntime = await asyncPython({
      fs: 'mem',
    });

    await py.exec(
      [
        'import sys, builtins',
        'class __SpBlocker:',
        "    def find_spec(self, fullname, path=None, target=None):",
        "        if fullname in ('js', '_js') or fullname.startswith('js.'):",
        "            raise ImportError('js disabled')",
        "        if fullname in ('subprocess', 'socket', 'http', 'urllib', 'ftplib', 'smtplib', 'telnetlib'):",
        "            raise ImportError('restricted module')",
        "        return None",
        'sys.meta_path.insert(0, __SpBlocker())',
        'for mod in ("js","_js","subprocess","socket"):',
        '    sys.modules.pop(mod, None)',
      ].join('\n')
    );

    await py.exec(code);

    await py.exec(`
def __safe_lookup(key):
    try:
        return lookup(key)
    except KeyError:
        return None
    except Exception:
        return None

def __safe_reverse_lookup(value):
    try:
        if 'reverse_lookup' in globals():
            return list(reverse_lookup(value))
        return []
    except Exception:
        return []
`);

    const hasLongestKey = await py.repr("'LONGEST_KEY' in dir()");
    if (hasLongestKey.trim() !== 'True') {
      throw new Error('Invalid or missing LONGEST_KEY in python dictionary');
    }
    const longestRaw = await py.repr('int(LONGEST_KEY)');
    const pythonLongest = Number.parseInt(String(longestRaw).replace(/[^0-9-]/g, ''), 10);
    if (!Number.isFinite(pythonLongest) || pythonLongest <= 0) {
      throw new Error('Invalid or missing LONGEST_KEY in python dictionary');
    }
    this._longestKey = pythonLongest;

    const hasLookup = await py.repr('callable(lookup) if "lookup" in dir() else False');
    if (hasLookup.trim() !== 'True') {
      throw new Error('Missing or invalid `lookup` function in python dictionary');
    }

    const hasReverse = await py.repr('callable(reverse_lookup) if "reverse_lookup" in dir() else False');
    this._hasReverseLookup = hasReverse.trim() === 'True';

    const hasDict = await py.repr("'DICTIONARY' in dir()");
    if (hasDict.trim() === 'True') {
      try {
        const raw = await py.repr(
          "__import__('json').dumps([[list(k), v] for k, v in DICTIONARY.items() if isinstance(k, tuple) and isinstance(v, str)])"
        );
        const trimmed = String(raw).trim().replace(/^'|'$/g, '');
        const parsed = JSON.parse(trimmed);
        if (Array.isArray(parsed)) {
          this._entries = parsed.filter(
            (item): item is [string[], string] =>
              Array.isArray(item) && Array.isArray(item[0]) && typeof item[1] === 'string'
          );
          this._length = this._entries.length;
          if (this._entries.length > 0) {
            const maxLen = Math.max(...this._entries.map(([s]) => s.length));
            if (maxLen > this._longestKey) {
              this._longestKey = maxLen;
            }
          }
        }
      } catch {
        // Ignore enumeration errors; keep dictionary usable for lookups.
      }
    }

    this._py = py;
  }

  get path(): string {
    return this._path;
  }

  set path(value: string) {
    this._path = value;
  }

  get longestKey(): number {
    return this._longestKey;
  }

  get length(): number {
    return this._length >= 0 ? this._length : -1;
  }

  async get(strokeTuple: string[]): Promise<string | null> {
    if (!this._py) {
      return null;
    }
    if (strokeTuple.length > this._longestKey) {
      return null;
    }

    try {
      const tupleStr = `(${strokeTuple.map(s => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`).join(', ')}${strokeTuple.length === 1 ? ',' : ''})`;
      const result = await this._py.repr(`__safe_lookup(${tupleStr})`);

      const trimmed = result.trim();
      if (trimmed && trimmed !== 'None') {
        if ((trimmed.startsWith("'") && trimmed.endsWith("'")) ||
            (trimmed.startsWith('"') && trimmed.endsWith('"'))) {
          return trimmed.slice(1, -1);
        }
        return trimmed;
      }
      return null;
    } catch {
      return null;
    }
  }

  has(strokeTuple: string[]): boolean {
    const key = strokeTuple.join('/');
    return this._entries.some(([stroke]) => stroke.join('/') === key);
  }

  set(_strokeTuple: string[], _translation: string): void {
    throw new Error('Unsupported operation: Python dictionary is read-only');
  }

  delete(_strokeTuple: string[]): boolean {
    throw new Error('Unsupported operation: Python dictionary is read-only');
  }

  clear(): void {
    throw new Error('Unsupported operation: Python dictionary is read-only');
  }

  update(_entries: Iterable<[string[], string]>): void {
    throw new Error('Unsupported operation: Python dictionary is read-only');
  }

  *entries(): Generator<[string[], string]> {
    if (this._entries.length === 0) return;
    for (const entry of this._entries) {
      yield [entry[0], entry[1]];
    }
  }

  items(): Array<[string[], string]> {
    return [...this._entries];
  }

  async reverseLookup(translation: string): Promise<Set<string[]>> {
    if (this._entries.length > 0 && !this._hasReverseLookup) {
      return new Set(this._entries.filter(([, value]) => value === translation).map(([stroke]) => stroke));
    }

    if (!this._py || !this._hasReverseLookup) {
      return new Set();
    }

    try {
      const escapedTranslation = translation.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

      await this._py.exec(`import json; __reverse_result = json.dumps([list(s) for s in __safe_reverse_lookup('${escapedTranslation}')])`);
      const result = await this._py.repr('__reverse_result');

      const trimmed = result.trim();
      if (trimmed && trimmed !== "'[]'" && trimmed !== '[]') {
        try {
          const parsed = JSON.parse(trimmed.replace(/^'|'$/g, ''));
          if (Array.isArray(parsed)) {
            return new Set(parsed.filter(Array.isArray));
          }
        } catch {
          // ignore parse errors
        }
      }
      return new Set();
    } catch {
      return new Set();
    }
  }

  caseReverseLookup(_translation: string): Set<string> {
    return new Set();
  }

  terminate(): void {
    if (this._py) {
      this._py.terminate();
      this._py = null;
    }
  }
}
